#include <iostream>

// Needed for windows.. (This should be defined by cmake)
// #define BOOST_UUID_RANDOM_PROVIDER_FORCE_WINCRYPT
#include "boost/uuid/uuid.hpp"
#include "boost/uuid/uuid_io.hpp"
#include "boost/uuid/uuid_generators.hpp"

#include "lib_static.h"
#include "lib_dyn.h"
#include "lib_interface.h"

namespace b_uuid = boost::uuids;

int main(int argc, char** argv)
{
  std::cout << "Hello from main.cpp" << std::endl;

  LibStatic::hi_fn();
  LibDynamic::hi_fn();
  LibHeaderOnly::hi_fn();

  std::cout << "Random uuid generated by Boost::uuid" << std::endl;
  b_uuid::uuid uuid{ b_uuid::random_generator()() };
  std::cout << uuid << std::endl;

  return 0;
}
